Feature/top bar
le-huy-jh/Social-network pull request #3
Opened 2022-04-15 06:39 UTC by le-huy-jh

2022-04-15 06:56 UTC, anh-dinh-jh requested changes

2022-04-15 06:56 UTC, anh-dinh-jh commented on social-network/src/App.js
> +      }
Can we rewrite this logic without if-else?

2022-04-15 06:56 UTC, anh-dinh-jh commented on social-network/src/App.js
> +          isAuth={this.state.isAuth}
Please use object destructuring instead of calling this.state.* multiple times

2022-04-15 06:56 UTC, anh-dinh-jh commented on social-network/src/components/Header/Header.css
> +  }
Please remove all commented code

2022-04-15 06:56 UTC, anh-dinh-jh commented on social-network/src/components/Header/Header.js
> +  let navigate = useNavigate();
Will the value of `navigate` change in the future? Why do we have to use `let` for this?

2022-04-15 06:56 UTC, anh-dinh-jh commented on social-network/src/components/Sidebar/Sidebar.js
> +  let navigate = useNavigate();
Same as the above comment

2022-04-15 06:56 UTC, anh-dinh-jh commented on social-network/src/components/Sidebar/Sidebar.js
> +  }
Could we rewrite this logic?

2022-04-18 10:26 UTC, trangpham-jh requested changes

2022-04-18 10:26 UTC, trangpham-jh commented on social-network/src/components/Sidebar/Sidebar.js
> +  isAuth: PropTypes.bool,
You should use object destructuring here

2022-04-18 10:26 UTC, trangpham-jh commented on social-network/src/components/Sidebar/Sidebar.css
> +  row-gap: 10px;
Could you double-check if the row gap works on Safari?

2022-04-18 10:26 UTC, trangpham-jh commented on social-network/src/components/Sidebar/SidebarItem/SidebarItem.js
> +};
Same as above

2022-04-19 02:37 UTC, le-huy-jh commented on social-network/src/components/Sidebar/Sidebar.css
> +  row-gap: 10px;
I see it works on Safari

2022-04-19 03:34 UTC, le-huy-jh commented on social-network/src/components/Sidebar/SidebarItem/SidebarItem.js
> +  icon: PropTypes.func,
i have checked again. the type is function.

2022-04-19 04:48 UTC, merged